algoritmo "semnome"
// Função :
// Autor :
// Data : 03/03/2020
// Seção de Declarações 
var
A,B,C,X1,X2: REAL
inicio
// Seção de Comandos
escreval ("digite o valor de A: ")
leia (A)
escreval ("digite o valor de B: ")
leia (B)
escreval ("digite o valor de C com o caractere de subtração: ")
leia (C)
X1:=(-B+RaizQ(B^2-4*A*C))/2*A)
X2:=(-B-RaizQ(B^2-4*A*C))/2*A)
escreval ("o resultado de X1 é: ", X1, "o de X2 é:", X2)
fimalgoritmo
