algoritmo "2050"
// Função :
// Autor :
// Data : 18/02/2020
// Seção de Declarações 
var
nasc, ano2, ano5, idade, idade5: inteiro
inicio
// Seção de Comandos 
escreva (" digite seu ano de nascimento: ")
leia (nasc)
escreva (" digite o ano atual: ")
leia (ano2)
idade:= ano2-nasc
idade5:= 2050-ano2+idade
escreval (" sua idade atual é de: ", idade)
escreva (" e em 2050 você terá: ", idade5)
fimalgoritmo
