algoritmo "semnome"
// Função :
// Autor :
// Data : 03/03/2020
// Seção de Declarações 
var
salB, salG, salI, sal: real
inicio
// Seção de Comandos escreval ("
escreval ("digite o salário base R$: ")
leia (salB)
salI:= salB*0.11
escreval ("o imposto será de R$: ", salI)
sal:= salB-salI
escreval ("subtraindo o salário será de R$: ", sal)
salG:= sal+500
escreval ("o salário contando com imposto e gratificação será de R$: ", salG)

fimalgoritmo
