algoritmo "semnome"
// Função :
// Autor :
// Data : 02/06/2020
// Seção de Declarações 
var
cont, valor,quantos, total: inteiro
inicio
// Seção de Comandos
para cont <- valor ate 10 faca
escreva ("digite um numero: ")
leia (valor)
se ((valor>0) e (valor<=10)) entao
quantos <- quantos + 1
fimse
fimpara
total <- quantos
escreval ("números digitado entre 0 e 10 totalizaram: ", total," vezes")
fimalgoritmo
