algoritmo "semnome"
// Função :
// Autor :
// Data : 10/03/2020
// Seção de Declarações 
var
pes, pol, jad, mil: real
inicio
// Seção de Comandos 
escreval (" digite um número em pés para a conversão do mesma para as demais medidas: " )
leia (pes)
pol:= pes*12
jad:= pes/3
mil:= pes/5280
escreval ("convertidos ficam da seguinte forma: ")
escreval ("em polegadas: ", pol)
escreval ("em jardas: ", jad)
escreval ("em milhas: ", mil)
fimalgoritmo
