algoritmo "semnome"
// Função :
// Autor :
// Data : 10/03/2020
// Seção de Declarações 
var
n1,n2,result: real
inicio
// Seção de Comandos 
escreval ("dois números maiores que zero, eles serão calculados")
escreval ("serão mostrados um elevado ao outro")
escreval ("digite um número: ")
leia (n1)
escreval ("digite o outro: ")
leia (n2)
result:= n1^n2
escreval ("o resultado é: ", result)
fimalgoritmo
