algoritmo "semnome"
// Função :
// Autor :
// Data : 03/03/2020
// Seção de Declarações 
var
sal, Nsal,comp: real
inicio
// Seção de Comandos 
escreval ("o salário dos funcionários da empresa receberaão um aumento de 25%")
escreval ("digite o seu salário bruto: ")
leia (sal)
Nsal:= sal*0.25
comp:= Nsal+sal
escreval ("seu salário aumentou R$: ", Nsal)
escreval ("somando terá resultado de R$: ", comp)
fimalgoritmo
